name: 'GitHub Action for Yarn'
description: 'Wraps the yarn CLI to enable common yarn commands'
inputs:
  cmd:
    description: 'Yarn command'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
