name: CI

on: [push, pull_request]

jobs:
  run:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Docker Lint
        uses: docker://replicated/dockerfilelint
        with:
          args: Dockerfile
      - name: Shell Lint
        uses: actions/bin/shellcheck@master
        with:
          args: entrypoint.sh
      - name: Test
        uses: actions/bin/bats@master
        with:
          args: test/*.bats
